### ISSUE TITLE
Consistent grid style

### ISSUE THREAD

**Issue by chrishutchinson** [journalisttoolbox/journalisttoolbox-front-end#85]
At present there are two different grid styles, one for search, and another for featured lists. We should make this consistent and choose one, with my preference being the card style layout on the featured tool list (although, I'm happy to swap out the text we have there with other information more appropriate for search).

<img width="571" alt="screen shot 2015-11-27 at 14 48 59" src="https://cloud.githubusercontent.com/assets/1573022/11443591/321d7d64-9516-11e5-8a56-51c8b438c91c.png">
<img width="576" alt="screen shot 2015-11-27 at 14 49 05" src="https://cloud.githubusercontent.com/assets/1573022/11443590/321d6658-9516-11e5-825a-a393edbe607b.png">

**Comment by nevosegal** [comment]
@haslaa01, what do you say? You can suggest something completely different if you feel like it :D

**Comment by haslaa01** [comment]
Hi @nevosegal,

I completely agree that it would be better to present the tools to the user in a consistent way across the site, as I feel that it would allow users to familiarise themselves with the visual language faster and would eliminate the risk of any confusion arising.

I also agree that the card style used on the featured lists is the more suitable choice of the two at current, for the following two reasons: 
- There isn't a clear distinction between the background and the other cards, which is visually confusing (even if it could be resolved by [changing the background colour to grey](https://trello.com/c/KfyDvxeK/73-suggestion-set-background-colour-to-grey)))
- There is no way for a user to quickly comprehend (without hovering over the cards themselves) the purpose or utility of a tool, which places unnecessary physical burden on them and (potentially less importantly) means that mobile and tablet users have no means by which to discover the nature of a tool without opening the associated page

With that said, I do think that the current size of the larger card is potentially unsuitable for longer lists (as it would require users to scroll ~2x as much in order to view the same content), so it may be worth exploring ways that the crucial information could be conveyed in a more concise way.

For example, you could combine both styles and partially transparently overlay the text over the logo, as is shown in the example below and (if users wish to see more, they could potentially hover over the image to hide the text):

![infogram-3](https://cloud.githubusercontent.com/assets/8749447/11713257/2bb37f46-9f2a-11e5-83d1-2072ba4ba37f.png)

I understand there would be a risk of the page appearing cluttered if this approach was adopted, as I have not seen what it would look like if all of the cards were updated in this way, but I still think it is worth considering a similar approach, if it seems suitable.

I appreciate that some members of the team may be averse to the idea of partially obscuring logos in the default view, given that logos are aesthetically-pleasing and eye-catching (and supposedly representative of the products), but most of the time I do not feel they really convey what the associated products actually do, so, somewhat contrary to intuition, it may be important to place a greater emphasis on the product descriptions than the site currently does. 

On that point, I have noticed that some of the descriptions are somewhat vague (the **info.gram** description is a good example of this) and others unnecessarily long, so, if there is the time and resources available, I think it would be worth thinking about whether it would be possible to update some of the descriptions so that they convey the most useful points in as few words as possible.

For example, for "Resize Image", it might be better to just say:
 _"Resize and share images to Facebook, Twitter and Instagram from your iPhone "_ 
rather than:
_""Resize images with ease by using Resize Image. A beautifully designed interface allows you to edit quickly and easily. You then have access to a range of sharing options, such as Facebook, Twitter and Instagram. Resize Image has been fully optimised for the new iPhone 5 to take advantage of the latest technology."_

(at current, the part about the iPhone is truncated from the grid view, so users would have to view the product page before they discovered it was iPhone-only, assuming they hadn't utilised the filters)

I assume that most, if not all, of the information has been taken directly from the associated product websites themselves in order to save time, but I think it would drastically improve the user experience if users were offered a way to comprehend the purpose of a tool without having to read marketing jargon.

Perhaps something to consider post-launch?
