### ISSUE TITLE
Range of tools available

### ISSUE THREAD

**Issue by chrishutchinson** [journalisttoolbox/journalisttoolbox-front-end#91]
Before launch we should go through the list of tools and make sure we've got the selection right.

I'm concerned that journalists that aren't aware of many tools (less technical users generally), may get thrown when they see tools like RStudio any a multitude of .js libraries in their search results.

A solution to that might be to have a "regular search" and a "power" search, but that may need more thought.

I'm keen for launch that 90% of tools have live demos and have good, simply written descriptions. I'd much rather go with quality of tool over quantity. I've logged it as a GitHub issue are it's something I thought about while logging other issues, but I think it'll need more discussion, so will x-post into Slack.

**Comment by haslaa01** [comment]
I agree that quality should take precedence over quantity - after all, it doesn't take many bad experiences of a site to scare people off! :smile: 

Given this, I think offering either a filter or some other means by which users could refine their search would be a very useful feature, because, as you say, if users feel alienated by the nature of the products they see, they are unlikely to feel comfortable using the site.

**Comment by nevosegal** [comment]
At the moment we have simple filters implemented, and for launch the editorial team cherry-picked 60 tools for which they wrote good descriptions.
